name: Publish Patch (patch-*)
on:
  push:
    branches:
      - 'patch-*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          check-latest: true
      - name: Check Node version
        run: node -v
      - name: Update NPM version
        run: npm install -g "npm@^10.9.2"
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Configure NPM
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
      - name: Publish
        run: |
          npm run version:exit
          npm run version:pkgs
          git commit -am "chore: exit prerelease mode"
          npm run release
          git push --follow-tags
      - name: Get Alias
        id: info
        run: |
          echo "::set-output name=alias::$(npm run --silent getAlias)"
          echo "::set-output name=version::$(npm run --silent getVersion)"
      - name: Build Docs
        run: npm run build:docs
        env:
          PATH_PREFIX: /version/${{ steps.info.outputs.version }}
      - name: Deploy Docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ steps.info.outputs.alias }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Build Landing Page
        run: npm run build:landing
      - name: Update landing page on Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-landing/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy Landing page from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
