name: Publish
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Check Node version
        run: node -v
      - name: Check NPM version
        run: npm -v
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Coverage
        uses: codecov/codecov-action@v1
      - name: Configure NPM
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
      - name: Publish (Latest)
        if: github.ref == 'refs/heads/main'
        run: |
          npm run publish -- --conventional-graduate --yes
      - name: Publish (Next)
        if: github.ref == 'refs/heads/dev'
        run: |
          npm run publish -- --conventional-prerelease --yes
      - name: Get Alias
        id: info
        run: |
          echo "::set-output name=alias::$(npm run --silent getAlias)"
          echo "::set-output name=version::$(npm run --silent getVersion)"
      - name: Build Next Docs
        if: github.ref == 'refs/heads/dev'
        run: npm run build:docs
        env:
          PATH_PREFIX: /version/next
      - name: Deploy Next Docs to Netlify
        if: github.ref == 'refs/heads/dev'
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: next
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Build Latest Docs
        if: github.ref == 'refs/heads/main'
        run: npm run build:docs
        env:
          PATH_PREFIX: /version/${{ steps.info.outputs.version }}
      - name: Deploy Latest Docs to Netlify
        if: github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ steps.info.outputs.alias }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Build Landing Page
        run: npm run build:landing
      - name: Update landing page on Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-landing/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy Landing page from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Sync main -> dev
        if: github.ref == 'refs/heads/main'
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: main
          target-branch: dev
